### ISSUE TITLE
Bug - Update causes post type chage to post instead of spponsor

### ISSUE THREAD

**Issue by ieugen** [igorbenic/wp-sponsors#14]
Hello, 

I've just installed your plugin and it's quite usefull. However I have noticed a bug. 
The Sponsors custom type is not displayed in all drop down menus and when you edit the post type and click update, the post type is changed to Post. 

Since the post type is not visible on the post view in admin, I can't change the post back to Sponsors type. I'm using `Post Type Switcher` to change post types. 
All plugins are up to date. Wordpress version is 4.8.1 . I'm using Advanced Custom Fields and also Custom Post Type UI plugins. Deployment is done on Debian Stretch 9.1 with php 7. - default in Debian. 

`Sponsors` post type is not visible:
- on the post edit page (in the Post Type Switcher dropdown)
- in the quick edit screen on the Sponsors list

Once the change is made I can't turn the post back unless I use the database (did not try that yet). 

I've attached images with the quick view. 
An update would be very welcomed. 

![selec ie_002](https://user-images.githubusercontent.com/1050920/30214319-a4eb77a2-94b4-11e7-925f-61b28f460f90.png)
![meniu_001](https://user-images.githubusercontent.com/1050920/30214331-abb5d9ba-94b4-11e7-81a1-87cab80595f6.png)

**Comment by igorbenic** [comment]
Hi, tried it myself. It seems that it was an error with that plugin. 3.0.0 of their version seems to fix it as they note in their changelog "Fix bug causing some post-types to switch unexpectedly".
